name: robot_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        # Install Salesforce CLI
        - name: Install Salesforce CLI
          run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install

        # Checkout the code in the pull request
        - name: 'Checkout source code'
          uses: actions/checkout@v2
              
        - name: Install pipx
          run: |
              pip install pipx
        - name: Install cumulusci
          run: |
              pipx install cumulusci
              sfdx force:auth:web:login --setalias DevHub --instanceurl https://sem-ag-devhub--qafull.sandbox.my.salesforce.com
#              
              
#         # Create scratch org
                               
#         - name: Build Org and Execute Tests
#           run: |
#             cci flow run MyDevOrg --org dev
#             cci task run robot --org dev -o vars BROWSER:headlesschrome
            
#         - name: Store robot test results
#           uses: actions/upload-artifact@v1
#           with:
#            name: robot test reports
#            path: robot_test/results
#         #- name: Delete Scratch Org
#          # if: ${{ always() }}
#          # run: |
#           # cci org scratch_delete dev
              
              

# #         # Add Comment with Scratch Org URL
# #         - uses: marocchino/sticky-pull-request-comment@v2
# #           with:
# #             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# #             message: |
# #               Review package - [Scratch Org](${{steps.login.outputs.login-url}})
