name: robot_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
        # Install Salesforce CLI
        - name: Install Salesforce CLI
          run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install

        # Checkout the code in the pull request
        - name: 'Checkout source code'
          uses: actions/checkout@v2

        - name: Install PIPX
            run:|
              python pip install pipx
              python pipx ensurepath
              python install cumulusci
              
        # Create scratch org

        - name: list available ORGs
            run:|
              pip install pipx
              pipx ensurepath
              pipx install cumulusci
              cci --version
              cci org list
              cci org info dev
              cci org scratch dev myDevOrg
              
              

#         # Add Comment with Scratch Org URL
#         - uses: marocchino/sticky-pull-request-comment@v2
#           with:
#             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#             message: |
#               Review package - [Scratch Org](${{steps.login.outputs.login-url}})
